version: 2.1
jobs:
  compile:
   docker:
      - image: gitpod/workspace-full:latest
   steps:
      - run:
          command: |
           sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install wget curl git neofetch
           git config --global user.name "x0rzavi"
           git config --global user.email "x0rzavi@gmail.com"
           git config --global color.ui true
           neofetch
           df -h
           free -h
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
