version: 2.1
jobs:
  compile:
   docker:
      - image: gitpod/workspace-full:latest
   steps:
      - run:
          command: |
           sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install wget curl git neofetch
           neofetch
           git config --global user.name "x0rzavi"
           git config --global user.email "x0rzavi@gmail.com"
           git config --global color.ui true
           git clone https://github.com/x0rzavi/gitpod_template_repo
           cd gitpod_template_repo
           sudo chmod a+x setup.sh
           ./setup.sh
           mkdir -p android/lineage
           cd android/lineage
           repo init -u https://github.com/LineageOS/android.git -b lineage-17.0 --depth=1
           repo sync
workflows:
  version: 2.1
  cooking:
    jobs:
      - compile
