version: 2.1
jobs:
  compile:
   docker:
      - image: gitpod/workspace-full:latest
   steps:
      - run:
          command: |
           sudo apt-get -y update && sudo apt-get -y upgrade && sudo apt-get -y install wget curl git neofetch
           git config --global user.name "x0rzavi"
           git config --global user.email "x0rzavi@gmail.com"
           git config --global color.ui true
           git clone https://github.com/x0rzavi/gitpod_template_repo
           chmod a+x gitpod_template_repo/setup.sh
           ./setup.sh
           mkdir -p android/lineage
           cd android/lineage
           repo init -u https://github.com/LineageOS/android.git -b lineage-17.1 --depth=1
           repo sync -j16 -c
           git clone https://github.com/adislice/android_device_xiaomi_ugglite -b lineage-17.0 device/xiaomi/ugglite
           git clone https://github.com/adislice/android_vendor_xiaomi_ugglite -b lineage-17.0 vendor/xiaomi
           git clone https://github.com/x0rzavi/android_kernel_xiaomi_msm8917 -b unity --depth=1 kernel/xiaomi/msm8937
           source build/envsetup.sh
           lunch lineage_ugglite-userdebug
           mka bacon -j16
           
workflows
  version: 2.1
  cooking:
    jobs:
      - compile
